# -*- coding: utf-8 -*-
"""Dictionary.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EEP6UDUtbxFBhnJG8qFIjd662oukUh22

Dictionary
"""

d={}

type(d)

d={1:1,2:'a',3:'o'}
print(d)
d.



"""# Creating an empty Dictionary
Dict = {}
print("Empty Dictionary: ")
print(Dict)
  
# Adding elements one at a time
Dict[0] = 'Geeks'
Dict[2] = 'For'
Dict[3] = 1
print("\nDictionary after adding 3 elements: ")
print(Dict)
  
# Adding set of values 
# to a single Key
Dict['Value_set'] = 2, 3, 4
print("\nDictionary after adding 3 elements: ")
print(Dict)
  
# Updating existing Key's Value
Dict[2] = 'Welcome'
print("\nUpdated key value: ")
print(Dict)
  
# Adding Nested Key value to Dictionary
Dict[5] = {'Nested' :{'1' : 'Life', '2' : 'Geeks'}}
print("\nAdding a Nested Key: ")
print(Dict)
"""

d[0]='Geeks'
print(d)

d[4]='Value'
print(d)
d[1]='welcome'
print(d)

d[2]='why'
print(d)
d[7]='pop'
print(d)

"""Iterating each value in dictionary"""

for value in d:
  print(value)

for name,fav_subject in favorite_subjects.items():
    print(f"{name} likes {fav_subject}")

for i in d:
  print(d)

for key in d.items():
  print(key)

for key in d.keys():
  print(key)

a_dict = {'color': 'blue', 'fruit': 'apple', 'pet': 'dog'}
for value in a_dict:
     print(value)

dict1={1:'abc',2:'xyz',3:'uvw'}
for key in dict1.items():
  print(key)



for values in dict1.values():
  print(values)

for keys in dict1.keys():
  print(keys)

print(dict1)

#dict1[4].append('why')
print(dict1)

#del dict1[4]
print(dict1)

for values in dict1.values():
  print(values)

dict1.pop(2)

print(dict1)



dict2={}

"""Method	Description
clear()	It will remove all the elements from the dictionary.
append()	It is a built-in function in Python that helps to update the values for the keys in the dictionary.
update()	The update() method will help us to merge one dictionary with another.
pop()	Removes the element from the dictionary.


"""

list1=[2,3,4,5,6]
for i in list1:
    sum+=i
print(sum)

